### ISSUE TITLE
gr-dpd blocks in real-time with a LimeSDR

### ISSUE THREAD

**Issue by susanalainez** [gnuradio/gr-dpd#13]
We're trying to use the gr-dpd blocks in real-time with a LimeSDR.  However, we're finding that samples are being dropped and we think that it might have to do with computing limitations associated with the blocks. Has anyone else run into these problems in the past? Any ideas on how we could address the issues?

**Comment by alekhgupta1441** [comment]
Thanks @susanalainez  for reporting the issue. I would like to know which mode of predistorter you have used or post your flowgraph here. Although I would also like to point out that the gr-dpd is currently having limitations for real-time training due to issues #8 & #11. Using LimeSDR can have potential synchronisation issues.
Any suggestions or contributions to address these issues are highly appreciated.
